//LOCALHOST
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/63d27ea49d69c1f3522b9d7b
###
GET http://localhost:3000/contacts/63d27edd9d69c1f3522b9d7c
###
GET http://localhost:3000/contacts/63bdfe79ec5a9caef7714318
###
POST  http://localhost:3000/contacts
content-type:application/json

{
    "firstName": "Roberto",
    "lastName": "Quiroz",
    "email": "robertoquiroz@gmail.com",
    "favoriteColor": "White",
    "birthday": "12/13/1984"
}

###
PUT http://localhost:3000/contacts/63d27efd9d69c1f3522b9d7d
content-type:application/json

{
    "firstName": "Roberto",
    "lastName": "Quiroga",
    "email": "robertoquiroz@gmail.com",
    "favoriteColor": "White",
    "birthday": "12/13/1984"
}
###
DELETE http://localhost:3000/contacts/63d27f1c9d69c1f3522b9d7e


//RENDER - DEPLOY
###
GET https://cse341-webserver.onrender.com/contacts
###
GET https://cse341-webserver.onrender.com/contacts/63ca7a0b9f788ebbfc377676
###
GET https://cse341-webserver.onrender.com/contacts/63bdfdfeec5a9caef7714317
###
GET https://cse341-webserver.onrender.com/contacts/63bdfe79ec5a9caef7714318
###
POST  https://cse341-webserver.onrender.com/contacts
content-type:application/json

{
    "firstName":"Maria",
    "lastName":"godoy",
    "email":"mariadelosangeles@gmail.com",
    "favoriteColor":"none",
    "birthday":"11/05/1995"
}

###
PUT https://cse341-webserver.onrender.com/contacts/63ca7a0b9f788ebbfc377676
content-type:application/json

{
    "firstName":"Maria",
    "lastName":"godoy",
    "email":"mariadelosangeles@gmail.com",
    "favoriteColor":"red",
    "birthday":"11/05/1995"
}


###
DELETE https://cse341-webserver.onrender.com/contacts/63ca7a0b9f788ebbfc377676